[package]
name = "changes"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "3.0.5", features = ["derive"] }
edit = "0.1.2"
names = { version = "0.12.0", default-features = false }
thiserror = "1.0.30"
dialoguer = "0.9.0"
serde = '1.0'
serde-frontmatter = "0.1.0"
chrono = {version="0.4", features = ["serde"]}
strum_macros = "0.23"
strum = { version = "0.23", features = ["derive"] }
